"""sync_orm_drift

Revision ID: 640950af09ba
Revises: 20260525_156
Create Date: 2026-05-25 17:29:29.156671+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '640950af09ba'
down_revision: str | None = '20260525_156'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_av_attr_number'), table_name='attribute_values', postgresql_where='(value_number IS NOT NULL)')
    op.drop_index(op.f('idx_audit_events_entity_type_event_at'), table_name='audit_events')
    op.alter_column('audit_hash_state', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_budgets_account'), table_name='budgets')
    op.alter_column('channels', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_index(op.f('ix_competitor_listings_embedding_hnsw'), table_name='competitor_listings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_cost_centers_code'), table_name='cost_centers')
    op.alter_column('costs', 'currency_origin',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('uq_costs_active_combo'), table_name='costs', postgresql_where="((status)::text = 'active'::text)")
    op.create_index('idx_costs_active_unique_lookup', 'costs', ['sku', 'scheme_code', 'supplier_code'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_costs_sku'), 'costs', ['sku'], unique=False)
    op.drop_index(op.f('idx_open_items_open'), table_name='customer_open_items', postgresql_where="(status <> 'paid'::text)")
    op.alter_column('dn_nps_reference', 'dn_nominal',
               existing_type=sa.TEXT(),
               comment="Tamaño nominal métrico sin prefijo DN: '80', '100'",
               existing_comment="Tamaño nominal métrico: '80', '100', '150' (sin prefijo DN)",
               existing_nullable=False)
    op.alter_column('dn_nps_reference', 'nps_nominal',
               existing_type=sa.TEXT(),
               comment="NPS sin comillas: '3', '4', '6'",
               existing_comment="Tamaño nominal americano: '3', '4', '6' (sin comillas)",
               existing_nullable=False)
    op.alter_column('dn_nps_reference', 'nps_label',
               existing_type=sa.TEXT(),
               comment='Etiqueta legible: \'3"\', \'4"\'',
               existing_comment='Etiqueta legible NPS: \'3"\', \'4"\', \'6"\'',
               existing_nullable=False)
    op.alter_column('dn_nps_reference', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Aclaraciones o excepciones de norma',
               existing_nullable=True)
    op.drop_index(op.f('uq_dn_nps_ref_dn'), table_name='dn_nps_reference')
    op.drop_index(op.f('idx_exception_rules_active_channel'), table_name='exception_rules')
    op.alter_column('family_schemas', 'family_slug',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Slug de familia (corresponde a families.code o registry futuro). Sin FK por ahora — evolutivo.',
               existing_nullable=False)
    op.alter_column('family_schemas', 'json_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON Schema Draft 2020-12; validado client + server',
               existing_nullable=False)
    op.drop_index(op.f('ix_force_logout_user_created'), table_name='force_logout_events')
    op.create_index('ix_force_logout_user_created', 'force_logout_events', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_fx_lookup_desc'), table_name='fx_rates')
    op.drop_index(op.f('ix_gl_accounts_code'), table_name='gl_accounts')
    op.drop_index(op.f('ix_gl_accounts_type'), table_name='gl_accounts')
    op.drop_index(op.f('idx_gr_received_at'), table_name='goods_receipts')
    op.create_index('idx_gr_received_at', 'goods_receipts', [sa.literal_column('received_at DESC')], unique=False)
    op.drop_index(op.f('ix_hitl_queue_first_appearance'), table_name='hitl_queue', postgresql_where="(((status)::text = 'pending'::text) AND (is_first_appearance = true))")
    op.drop_index(op.f('ix_hitl_queue_match_id'), table_name='hitl_queue', postgresql_where="((status)::text = 'pending'::text)")
    op.create_index('ix_hitl_queue_match_id', 'hitl_queue', ['match_id'], unique=False)
    op.drop_column('import_runs', 'orphans')
    op.add_column('inventory_alerts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_inv_pos_unrestricted'), table_name='inventory_positions', postgresql_where="(stock_type = 'unrestricted'::text)")
    op.drop_index(op.f('uix_inv_pos_5d'), table_name='inventory_positions', postgresql_where='((location_id IS NOT NULL) AND (lot_id IS NOT NULL))')
    op.drop_constraint(op.f('fk_inv_pos_lot'), 'inventory_positions', type_='foreignkey')
    op.drop_constraint(op.f('fk_inv_pos_location'), 'inventory_positions', type_='foreignkey')
    op.drop_constraint(op.f('fk_inv_pos_warehouse'), 'inventory_positions', type_='foreignkey')
    op.drop_index(op.f('idx_invoice_original_id'), table_name='invoices', postgresql_where='(original_invoice_id IS NOT NULL)')
    op.drop_index(op.f('idx_invoice_payment_terms_id'), table_name='invoices', postgresql_where='(payment_terms_id IS NOT NULL)')
    op.drop_index(op.f('ix_je_controls_type'), table_name='journal_entry_controls')
    op.drop_index(op.f('ix_je_controls_user'), table_name='journal_entry_controls')
    op.alter_column('kg_integrity_results', 'node_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kg_integrity_results', 'edge_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kg_integrity_results', 'orphan_nodes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kg_integrity_results', 'cdc_lag_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kg_integrity_results', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_kg_integrity_results_checked_at'), table_name='kg_integrity_results')
    op.alter_column('last_good_exports', 'channel_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('last_good_exports', 'scheme_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_last_good_exports_channel_scheme'), 'last_good_exports', type_='unique')
    op.create_index('uq_last_good_exports_channel_scheme', 'last_good_exports', ['channel_code', 'scheme_code'], unique=True)
    op.alter_column('match_candidates', 'price_confidence_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0-100: confiabilidad del precio según plazo de entrega vs stock UAE',
               existing_nullable=True)
    op.alter_column('match_candidates', 'pack_units',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unidades por pack (NULL o 1 = precio por unidad individual)',
               existing_nullable=True)
    op.drop_index(op.f('idx_match_candidates_calibrated'), table_name='match_candidates', postgresql_where='(calibrated_score IS NOT NULL)')
    op.drop_index(op.f('idx_match_candidates_label'), table_name='match_candidates', postgresql_where='(label IS NOT NULL)')
    op.drop_index(op.f('idx_mc_conf_lower'), table_name='match_candidates')
    op.drop_index(op.f('idx_mc_conf_upper'), table_name='match_candidates')
    op.drop_column('match_candidates', 'raw_payload_jsonb')
    op.drop_column('match_candidates', 'pipeline_version')
    op.drop_column('match_candidates', 'calibrator_version')
    op.drop_column('match_candidates', 'vlm_verdict')
    op.drop_column('match_candidates', 'fetched_at')
    op.drop_column('match_candidates', 'calibrated_score')
    op.drop_column('match_candidates', 'vlm_reasoning')
    op.drop_index(op.f('idx_match_rule_stats_candidate'), table_name='match_rule_stats')
    op.drop_index(op.f('idx_match_rule_stats_profile'), table_name='match_rule_stats')
    op.alter_column('material_aliases', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment='industry_standard | amazon_pdp | erp | manual',
               existing_nullable=True)
    op.alter_column('material_aliases', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('gen_random_uuid()'),
               type_=sa.UUID(),
               postgresql_using='id::uuid',
               existing_nullable=False)
    op.alter_column('model_dimension_rows', 'dn_secondary_mm',
               existing_type=sa.INTEGER(),
               comment='Solo para reductores (ej. reducción 1/2 x 3/8): DN salida',
               existing_nullable=True)
    op.alter_column('model_flow_data', 'mesh_mm',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment='Tamaño de malla en mm (ej. 1.8, 1.0)',
               existing_nullable=True)
    op.alter_column('model_tech_tables', 'gasket_material',
               existing_type=sa.TEXT(),
               comment='Solo para kind=pt_curve con múltiples juntas: EPDM | PTFE | GRAFITO',
               existing_nullable=True)
    op.drop_index(op.f('ix_payment_run_items_run'), table_name='payment_run_items')
    op.drop_index(op.f('ix_payment_runs_date'), table_name='payment_runs')
    op.drop_index(op.f('ix_payment_runs_status'), table_name='payment_runs')
    op.create_index('idx_payment_terms_code', 'payment_terms', ['code'], unique=False)
    op.drop_index(op.f('ix_period_close_fy_period'), table_name='period_close_checklists')
    op.drop_index(op.f('ix_posting_periods_fy'), table_name='posting_periods')
    op.drop_index(op.f('ix_price_alerts_notified_at'), table_name='price_alerts', postgresql_where='(notified_at IS NULL)')
    op.create_index(op.f('ix_price_approval_events_price_id'), 'price_approval_events', ['price_id'], unique=False)
    op.alter_column('price_calibration_ranges', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'AED'::bpchar"))
    op.drop_index(op.f('ix_price_history_raw_scraped_at'), table_name='price_history_raw')
    op.drop_index(op.f('ix_price_history_raw_sku'), table_name='price_history_raw', postgresql_where='(sku IS NOT NULL)')
    op.drop_index(op.f('ix_price_history_raw_match_marketplace'), table_name='price_history_raw')
    op.create_index('ix_price_history_raw_match_marketplace', 'price_history_raw', ['match_id', 'marketplace', 'scraped_at'], unique=False)
    op.alter_column('price_state_transitions', 'from_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('price_state_transitions', 'to_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_price_variances_period'), table_name='price_variances')
    op.drop_index(op.f('ix_price_variances_sku'), table_name='price_variances')
    op.drop_index(op.f('idx_prices_channel_status'), table_name='prices')
    op.drop_index(op.f('idx_prices_escalated'), table_name='prices', postgresql_where='(escalated = true)')
    op.drop_index(op.f('idx_prices_updated_at'), table_name='prices')
    op.drop_index(op.f('uq_prices_one_approved_active'), table_name='prices', postgresql_where="(((status)::text = 'approved'::text) AND (valid_to IS NULL))")
    op.create_index(op.f('ix_prices_product_sku'), 'prices', ['product_sku'], unique=False)
    op.create_index(op.f('ix_prices_status'), 'prices', ['status'], unique=False)
    op.alter_column('pricing_golden_tiers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('product_assets', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('idx_product_assets_locale'), table_name='product_assets', postgresql_where='(locale IS NOT NULL)')
    op.drop_index(op.f('idx_product_assets_status'), table_name='product_assets', postgresql_where="((status)::text <> 'archived'::text)")
    op.drop_constraint(op.f('product_images_storage_path_key'), 'product_assets', type_='unique')
    op.drop_constraint(op.f('uq_product_assets_hash_sha256'), 'product_assets', type_='unique')
    op.drop_constraint(op.f('uq_assets_bucket_path'), 'product_assets', type_='unique')
    op.create_index('uq_assets_bucket_path', 'product_assets', ['bucket', 'storage_path'], unique=True)
    op.alter_column('product_bore_dimensions', 'product_sku',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='SKU del producto',
               existing_nullable=False)
    op.alter_column('product_bore_dimensions', 'standard_system',
               existing_type=sa.VARCHAR(length=16),
               comment='DIN | ASME | AWWA | ISO | JIS | GOST',
               existing_comment='Sistema: DIN | ASME | AWWA | ISO',
               existing_nullable=False)
    op.alter_column('product_bore_dimensions', 'standard_code',
               existing_type=sa.TEXT(),
               comment="Ej: 'EN 558 Serie 20', 'ASME B16.10 Class 150', 'AWWA C504'",
               existing_comment="Código completo: 'EN 558 Serie 20', 'ASME B16.10 Class 150', 'AWWA C504'",
               existing_nullable=False)
    op.alter_column('product_bore_dimensions', 'pressure_class',
               existing_type=sa.VARCHAR(length=20),
               comment='PN6 | PN10 | PN16 | Class 150 | Class 300 | Class 600',
               existing_comment="Clase de presión aplicable: 'PN6', 'PN10', 'PN16', 'Class 150', 'Class 300'",
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'bore_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Diámetro de paso en mm — equiv. a dn_real del spec_viewer',
               existing_comment='Diámetro de paso (waterway bore) en mm — la dimensión que el spec llama dn_real',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'face_to_face_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Distancia cara a cara según la norma aplicable',
               existing_comment='Distancia cara a cara (construcción) en mm',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'end_to_end_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Distancia extremo a extremo (incluyendo bridas)',
               existing_comment='Distancia extremo a extremo (con bridas) en mm',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'flange_od_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Diámetro exterior de brida',
               existing_comment='Diámetro exterior de brida en mm',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'bolt_circle_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Diámetro del círculo de pernos',
               existing_comment='Diámetro del círculo de pernos en mm',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'bolt_count',
               existing_type=sa.INTEGER(),
               comment='Número de pernos de brida',
               existing_comment='Número de pernos/tornillos de brida',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'bolt_size',
               existing_type=sa.VARCHAR(length=16),
               comment='Tamaño de perno: \'M16\', \'5/8"\'',
               existing_comment='Tamaño de perno: \'M16\', \'5/8"\', etc.',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'is_primary',
               existing_type=sa.BOOLEAN(),
               comment='True si este es el estándar de referencia principal del producto',
               existing_comment='True si este estándar es el de referencia principal del producto',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_product_bore_dim_dn_ref'), table_name='product_bore_dimensions')
    op.alter_column('product_compatibility', 'kind',
               existing_type=postgresql.ENUM('spare_part', 'accessory', 'replaces', 'replaced_by', 'compatible_with', name='compatibility_kind'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('product_connections', 'connection_type',
               existing_type=postgresql.ENUM('flange', 'threaded', 'weld', 'press', 'push_fit', 'compression', 'other', name='connection_type'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('product_equivalences', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_equivalences', 'source',
               existing_type=sa.VARCHAR(length=200),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_equivalences', 'synced_to_kg',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_marketplace_listings', 'id',
               existing_type=sa.TEXT(),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('product_materials', 'material_grade',
               existing_type=sa.TEXT(),
               comment='ej. EN-GJL-250, AISI 304, CW617N',
               existing_nullable=True)
    op.alter_column('product_materials', 'material_standard',
               existing_type=sa.TEXT(),
               comment='ej. ASTM A307, UNE-EN-12165',
               existing_nullable=True)
    op.alter_column('product_materials', 'surface_treatment',
               existing_type=sa.TEXT(),
               comment='ej. Epoxy, Nickel, Zinc, None',
               existing_nullable=True)
    op.alter_column('product_models', 'connection_type',
               existing_type=sa.VARCHAR(length=32),
               comment='thread_bsp | thread_bspt | thread_npt | flange_en | flange_ansi',
               existing_nullable=True)
    op.drop_index(op.f('idx_product_models_active'), table_name='product_models')
    op.drop_index(op.f('idx_product_releases_status_active'), table_name='product_releases', postgresql_where="((status)::text = 'active'::text)")
    op.drop_constraint(op.f('uq_product_search_queries_sku_channel'), 'product_search_queries', type_='unique')
    op.drop_index(op.f('idx_pt_name_en_trgm'), table_name='product_translations', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where="((lang)::text = 'en'::text)")
    op.drop_column('product_translations', 'rejection_reason')
    op.drop_column('product_translations', 'staleness_reason')
    op.alter_column('product_uom_conversions', 'direction',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Sentido canónico: base_to_alt | alt_to_base | bidirectional',
               existing_nullable=True)
    op.alter_column('products', 'country_of_origin',
               existing_type=sa.TEXT(),
               server_default=sa.text("'ES'"),
               existing_nullable=True)
    op.alter_column('products', 'bore_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Bore real (waterway) en mm — estándar principal. Detalle en product_bore_dimensions.',
               existing_comment='Bore real del producto (estándar principal). Ej: 87.0 para DN80 wafer. Detalle completo por norma en product_bore_dimensions.',
               existing_nullable=True)
    op.alter_column('products', 'embedding_text',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    op.alter_column('products', 'embedding_image',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    op.drop_index(op.f('idx_products_active_lifecycle'), table_name='products', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_products_brand_id'), table_name='products')
    op.drop_index(op.f('idx_products_created_by'), table_name='products')
    op.drop_index(op.f('idx_products_data_quality'), table_name='products')
    op.drop_index(op.f('idx_products_display_pair_sku'), table_name='products')
    op.drop_index(op.f('idx_products_dn'), table_name='products')
    op.drop_index(op.f('idx_products_family_id'), table_name='products')
    op.drop_index(op.f('idx_products_family_not_deleted'), table_name='products', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_products_hs_code'), table_name='products')
    op.drop_index(op.f('idx_products_is_parent'), table_name='products', postgresql_where='(is_parent = true)')
    op.drop_index(op.f('idx_products_lifecycle_status'), table_name='products')
    op.drop_index(op.f('idx_products_material'), table_name='products')
    op.drop_index(op.f('idx_products_material_id'), table_name='products')
    op.drop_index(op.f('idx_products_model_id'), table_name='products')
    op.drop_index(op.f('idx_products_parent_sku'), table_name='products', postgresql_where='(parent_sku IS NOT NULL)')
    op.drop_index(op.f('idx_products_pn'), table_name='products')
    op.drop_index(op.f('idx_products_search_tsv'), table_name='products', postgresql_using='gin')
    op.drop_index(op.f('idx_products_series_id'), table_name='products')
    op.drop_index(op.f('idx_products_subfamily_id'), table_name='products')
    op.drop_index(op.f('idx_products_type_id'), table_name='products')
    op.drop_index(op.f('idx_products_updated_at'), table_name='products')
    op.drop_index(op.f('idx_products_updated_by'), table_name='products')
    op.drop_column('products', 'search_tsv')
    op.drop_index(op.f('ix_profit_centers_code'), table_name='profit_centers')
    op.alter_column('purchase_order_lines', 'price_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::text"))
    op.alter_column('purchase_orders', 'po_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'STANDARD'::text"))
    op.alter_column('purchase_requisitions', 'uom',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'UNIT'::text"))
    op.alter_column('purchase_requisitions', 'cost_center_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('purchase_requisitions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('purchase_requisitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_requisitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('purchase_requisitions_requester_id_fkey'), 'purchase_requisitions', type_='foreignkey')
    op.drop_constraint(op.f('purchase_requisitions_product_sku_fkey'), 'purchase_requisitions', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_requisitions', 'users', ['requester_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'purchase_requisitions', 'products', ['product_sku'], ['sku'], ondelete='SET NULL')
    op.alter_column('rfq_headers', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.drop_index(op.f('idx_rule_suggestions_profile_status'), table_name='rule_suggestions')
    op.drop_index(op.f('ix_brand_extractor_brand_marketplace'), table_name='scraper_brand_extractors')
    op.drop_index(op.f('uq_recipe_one_live_per_source'), table_name='scraper_source_recipes', postgresql_where='is_live')
    op.drop_index(op.f('ix_source_test_runs_source'), table_name='scraper_source_test_runs')
    op.alter_column('series', 'thread_standard',
               existing_type=sa.VARCHAR(length=32),
               comment='ISO 228-1 (BSP) | ISO 7/1 (BSPT) | ASME B1.20.1 (NPT)',
               existing_nullable=True)
    op.drop_index(op.f('idx_sl_warehouse'), table_name='source_list')
    op.drop_index(op.f('ix_standard_costs_fy'), table_name='standard_costs')
    op.drop_index(op.f('ix_standard_costs_sku'), table_name='standard_costs')
    op.drop_constraint(op.f('fk_stock_movements_lot'), 'stock_movements', type_='foreignkey')
    op.drop_constraint(op.f('fk_sm_warehouse'), 'stock_movements', type_='foreignkey')
    op.drop_constraint(op.f('fk_sm_location'), 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_tax_provisions_fy_period'), table_name='tax_provisions')
    op.drop_index(op.f('ix_tax_provisions_type'), table_name='tax_provisions')
    op.alter_column('taxonomy_aliases', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='NULL = alias permanente (e.g. rename); set para alias temporal',
               existing_nullable=True)
    op.alter_column('taxonomy_node_descendants', 'depth',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='0 = self; 1 = direct child; N = N-step descendant',
               existing_nullable=False)
    op.alter_column('taxonomy_nodes', 'parent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary parent (legacy single-parent tree). Multi-inheritance vive en taxonomy_node_parents.',
               existing_nullable=True)
    op.alter_column('taxonomy_nodes', 'labels',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='i18n labels: {es: ..., en: ..., ar: ...}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_nodes', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Validado contra family_schemas si aplicable',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_nodes', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='NULL = vigente; set para deprecar sin eliminar',
               existing_nullable=True)
    op.alter_column('taxonomy_nodes', 'superseded_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Nodo sucesor tras rename/fusión',
               existing_nullable=True)
    op.alter_column('taxonomy_nodes', 'node_acl',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='ACL granular opcional override del type. {visible_to_roles, editable_by_roles}',
               existing_nullable=True)
    op.alter_column('taxonomy_types', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='true = type núcleo (division, series, tier, material). Edición restringida; renaming sólo vía taxonomy_aliases.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('taxonomy_types', 'label_i18n',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='i18n labels: {es: ..., en: ..., ar: ...}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_types', 'depth_max',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='NULL = ilimitado; valida en INSERT/UPDATE de nodes',
               existing_nullable=True)
    op.alter_column('taxonomy_types', 'ui_layout',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='UI hints: {icon, custom_component, groups, position}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_types', 'governance_policy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{approval_required, allowed_creator_roles, max_nodes}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_types', 'external_mappings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{schema_org, google_taxonomy, amazon_aces}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_unmatched_offers_embedding'), table_name='unmatched_offers', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('unmatched_offers_fingerprint_key'), 'unmatched_offers', type_='unique')
    op.create_unique_constraint('uq_unmatched_offers_fingerprint', 'unmatched_offers', ['fingerprint'])
    op.drop_index(op.f('idx_users_delegate'), table_name='users')
    op.alter_column('vendor_invoices', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_index(op.f('ix_vendor_open_items_due'), table_name='vendor_open_items')
    op.drop_index(op.f('ix_vendor_open_items_status'), table_name='vendor_open_items')
    op.drop_index(op.f('ix_vendor_open_items_vendor'), table_name='vendor_open_items')
    op.drop_column('vendor_open_items', 'discount_days_deadline')
    op.drop_column('vendor_open_items', 'discount_pct')
    op.drop_column('vendor_open_items', 'discount_days')
    op.alter_column('vendor_product_conditions', 'vendor_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('vendor_product_conditions', 'uom',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'UNIT'::text"))
    op.alter_column('vendor_product_conditions', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'AED'::bpchar"))
    op.alter_column('vendor_product_conditions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('vendor_product_conditions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('vendor_product_conditions_vendor_id_product_sku_valid_from_key'), 'vendor_product_conditions', type_='unique')
    op.create_unique_constraint('uq_vpc_vendor_product_date', 'vendor_product_conditions', ['vendor_id', 'product_sku', 'valid_from'])
    op.drop_constraint(op.f('vendor_product_conditions_product_sku_fkey'), 'vendor_product_conditions', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_product_conditions', 'products', ['product_sku'], ['sku'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_product_conditions', type_='foreignkey')
    op.create_foreign_key(op.f('vendor_product_conditions_product_sku_fkey'), 'vendor_product_conditions', 'products', ['product_sku'], ['sku'])
    op.drop_constraint('uq_vpc_vendor_product_date', 'vendor_product_conditions', type_='unique')
    op.create_unique_constraint(op.f('vendor_product_conditions_vendor_id_product_sku_valid_from_key'), 'vendor_product_conditions', ['vendor_id', 'product_sku', 'valid_from'], postgresql_nulls_not_distinct=False)
    op.alter_column('vendor_product_conditions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_product_conditions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('vendor_product_conditions', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'AED'::bpchar"))
    op.alter_column('vendor_product_conditions', 'uom',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'UNIT'::text"))
    op.alter_column('vendor_product_conditions', 'vendor_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('vendor_open_items', sa.Column('discount_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vendor_open_items', sa.Column('discount_pct', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('vendor_open_items', sa.Column('discount_days_deadline', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_vendor_open_items_vendor'), 'vendor_open_items', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_open_items_status'), 'vendor_open_items', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_open_items_due'), 'vendor_open_items', ['due_date'], unique=False)
    op.alter_column('vendor_invoices', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.create_index(op.f('idx_users_delegate'), 'users', ['delegate_user_id'], unique=False)
    op.drop_constraint('uq_unmatched_offers_fingerprint', 'unmatched_offers', type_='unique')
    op.create_unique_constraint(op.f('unmatched_offers_fingerprint_key'), 'unmatched_offers', ['fingerprint'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_unmatched_offers_embedding'), 'unmatched_offers', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('taxonomy_types', 'external_mappings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='{schema_org, google_taxonomy, amazon_aces}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_types', 'governance_policy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='{approval_required, allowed_creator_roles, max_nodes}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_types', 'ui_layout',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='UI hints: {icon, custom_component, groups, position}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_types', 'depth_max',
               existing_type=sa.SMALLINT(),
               comment='NULL = ilimitado; valida en INSERT/UPDATE de nodes',
               existing_nullable=True)
    op.alter_column('taxonomy_types', 'label_i18n',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='i18n labels: {es: ..., en: ..., ar: ...}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_types', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='true = type núcleo (division, series, tier, material). Edición restringida; renaming sólo vía taxonomy_aliases.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('taxonomy_nodes', 'node_acl',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='ACL granular opcional override del type. {visible_to_roles, editable_by_roles}',
               existing_nullable=True)
    op.alter_column('taxonomy_nodes', 'superseded_by',
               existing_type=sa.UUID(),
               comment='Nodo sucesor tras rename/fusión',
               existing_nullable=True)
    op.alter_column('taxonomy_nodes', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL = vigente; set para deprecar sin eliminar',
               existing_nullable=True)
    op.alter_column('taxonomy_nodes', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Validado contra family_schemas si aplicable',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_nodes', 'labels',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='i18n labels: {es: ..., en: ..., ar: ...}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('taxonomy_nodes', 'parent_id',
               existing_type=sa.UUID(),
               comment='Primary parent (legacy single-parent tree). Multi-inheritance vive en taxonomy_node_parents.',
               existing_nullable=True)
    op.alter_column('taxonomy_node_descendants', 'depth',
               existing_type=sa.SMALLINT(),
               comment='0 = self; 1 = direct child; N = N-step descendant',
               existing_nullable=False)
    op.alter_column('taxonomy_aliases', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL = alias permanente (e.g. rename); set para alias temporal',
               existing_nullable=True)
    op.create_index(op.f('ix_tax_provisions_type'), 'tax_provisions', ['provision_type'], unique=False)
    op.create_index(op.f('ix_tax_provisions_fy_period'), 'tax_provisions', ['fiscal_year', 'period_num'], unique=False)
    op.create_foreign_key(op.f('fk_sm_location'), 'stock_movements', 'warehouse_locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_sm_warehouse'), 'stock_movements', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_stock_movements_lot'), 'stock_movements', 'inventory_lots', ['lot_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_standard_costs_sku'), 'standard_costs', ['product_sku'], unique=False)
    op.create_index(op.f('ix_standard_costs_fy'), 'standard_costs', ['fiscal_year'], unique=False)
    op.create_index(op.f('idx_sl_warehouse'), 'source_list', ['warehouse_id'], unique=False)
    op.alter_column('series', 'thread_standard',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='ISO 228-1 (BSP) | ISO 7/1 (BSPT) | ASME B1.20.1 (NPT)',
               existing_nullable=True)
    op.create_index(op.f('ix_source_test_runs_source'), 'scraper_source_test_runs', ['source_id', 'created_at'], unique=False)
    op.create_index(op.f('uq_recipe_one_live_per_source'), 'scraper_source_recipes', ['source_id'], unique=True, postgresql_where='is_live')
    op.create_index(op.f('ix_brand_extractor_brand_marketplace'), 'scraper_brand_extractors', ['brand_id', 'marketplace'], unique=False)
    op.create_index(op.f('idx_rule_suggestions_profile_status'), 'rule_suggestions', ['taxonomy_profile_id', 'status'], unique=False)
    op.alter_column('rfq_headers', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.drop_constraint(None, 'purchase_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'purchase_requisitions', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_requisitions_product_sku_fkey'), 'purchase_requisitions', 'products', ['product_sku'], ['sku'])
    op.create_foreign_key(op.f('purchase_requisitions_requester_id_fkey'), 'purchase_requisitions', 'users', ['requester_id'], ['id'], referent_schema='auth')
    op.alter_column('purchase_requisitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_requisitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_requisitions', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('purchase_requisitions', 'cost_center_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('purchase_requisitions', 'uom',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'UNIT'::text"))
    op.alter_column('purchase_orders', 'po_type',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'STANDARD'::text"))
    op.alter_column('purchase_order_lines', 'price_source',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::text"))
    op.create_index(op.f('ix_profit_centers_code'), 'profit_centers', ['pc_code'], unique=False)
    op.add_column('products', sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed('((setweight(to_tsvector(\'simple\'::regconfig, COALESCE(sku, \'\'::text)), \'A\'::"char") || setweight(to_tsvector(\'simple\'::regconfig, COALESCE(family, \'\'::text)), \'C\'::"char")) || setweight(to_tsvector(\'simple\'::regconfig, COALESCE(brand, \'\'::text)), \'D\'::"char"))', persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_products_updated_by'), 'products', ['updated_by'], unique=False)
    op.create_index(op.f('idx_products_updated_at'), 'products', ['updated_at'], unique=False)
    op.create_index(op.f('idx_products_type_id'), 'products', ['type_id'], unique=False)
    op.create_index(op.f('idx_products_subfamily_id'), 'products', ['subfamily_id'], unique=False)
    op.create_index(op.f('idx_products_series_id'), 'products', ['series_id'], unique=False)
    op.create_index(op.f('idx_products_search_tsv'), 'products', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_products_pn'), 'products', ['pn'], unique=False)
    op.create_index(op.f('idx_products_parent_sku'), 'products', ['parent_sku'], unique=False, postgresql_where='(parent_sku IS NOT NULL)')
    op.create_index(op.f('idx_products_model_id'), 'products', ['model_id'], unique=False)
    op.create_index(op.f('idx_products_material_id'), 'products', ['material_id'], unique=False)
    op.create_index(op.f('idx_products_material'), 'products', ['material'], unique=False)
    op.create_index(op.f('idx_products_lifecycle_status'), 'products', ['lifecycle_status'], unique=False)
    op.create_index(op.f('idx_products_is_parent'), 'products', ['is_parent'], unique=False, postgresql_where='(is_parent = true)')
    op.create_index(op.f('idx_products_hs_code'), 'products', ['hs_code'], unique=False)
    op.create_index(op.f('idx_products_family_not_deleted'), 'products', ['family'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_products_family_id'), 'products', ['family_id'], unique=False)
    op.create_index(op.f('idx_products_dn'), 'products', ['dn'], unique=False)
    op.create_index(op.f('idx_products_display_pair_sku'), 'products', ['display_pair_sku'], unique=False)
    op.create_index(op.f('idx_products_data_quality'), 'products', ['data_quality'], unique=False)
    op.create_index(op.f('idx_products_created_by'), 'products', ['created_by'], unique=False)
    op.create_index(op.f('idx_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('idx_products_active_lifecycle'), 'products', ['lifecycle_status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('products', 'embedding_image',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.alter_column('products', 'embedding_text',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.alter_column('products', 'bore_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Bore real del producto (estándar principal). Ej: 87.0 para DN80 wafer. Detalle completo por norma en product_bore_dimensions.',
               existing_comment='Bore real (waterway) en mm — estándar principal. Detalle en product_bore_dimensions.',
               existing_nullable=True)
    op.alter_column('products', 'country_of_origin',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('product_uom_conversions', 'direction',
               existing_type=sa.TEXT(),
               comment='Sentido canónico: base_to_alt | alt_to_base | bidirectional',
               existing_nullable=True)
    op.add_column('product_translations', sa.Column('staleness_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('product_translations', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_pt_name_en_trgm'), 'product_translations', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where="((lang)::text = 'en'::text)")
    op.create_unique_constraint(op.f('uq_product_search_queries_sku_channel'), 'product_search_queries', ['sku', 'channel'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_product_releases_status_active'), 'product_releases', ['product_sku'], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('idx_product_models_active'), 'product_models', ['active'], unique=False)
    op.alter_column('product_models', 'connection_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='thread_bsp | thread_bspt | thread_npt | flange_en | flange_ansi',
               existing_nullable=True)
    op.alter_column('product_materials', 'surface_treatment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ej. Epoxy, Nickel, Zinc, None',
               existing_nullable=True)
    op.alter_column('product_materials', 'material_standard',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ej. ASTM A307, UNE-EN-12165',
               existing_nullable=True)
    op.alter_column('product_materials', 'material_grade',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ej. EN-GJL-250, AISI 304, CW617N',
               existing_nullable=True)
    op.alter_column('product_marketplace_listings', 'id',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_equivalences', 'synced_to_kg',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('product_equivalences', 'source',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("'manual'::character varying"),
               existing_nullable=False)
    op.alter_column('product_equivalences', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.8'::double precision"),
               existing_nullable=False)
    op.alter_column('product_connections', 'connection_type',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('flange', 'threaded', 'weld', 'press', 'push_fit', 'compression', 'other', name='connection_type'),
               existing_nullable=False)
    op.alter_column('product_compatibility', 'kind',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('spare_part', 'accessory', 'replaces', 'replaced_by', 'compatible_with', name='compatibility_kind'),
               existing_nullable=False)
    op.create_index(op.f('idx_product_bore_dim_dn_ref'), 'product_bore_dimensions', ['dn_nominal_ref'], unique=False)
    op.alter_column('product_bore_dimensions', 'is_primary',
               existing_type=sa.BOOLEAN(),
               comment='True si este estándar es el de referencia principal del producto',
               existing_comment='True si este es el estándar de referencia principal del producto',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('product_bore_dimensions', 'bolt_size',
               existing_type=sa.VARCHAR(length=16),
               comment='Tamaño de perno: \'M16\', \'5/8"\', etc.',
               existing_comment='Tamaño de perno: \'M16\', \'5/8"\'',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'bolt_count',
               existing_type=sa.INTEGER(),
               comment='Número de pernos/tornillos de brida',
               existing_comment='Número de pernos de brida',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'bolt_circle_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Diámetro del círculo de pernos en mm',
               existing_comment='Diámetro del círculo de pernos',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'flange_od_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Diámetro exterior de brida en mm',
               existing_comment='Diámetro exterior de brida',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'end_to_end_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Distancia extremo a extremo (con bridas) en mm',
               existing_comment='Distancia extremo a extremo (incluyendo bridas)',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'face_to_face_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Distancia cara a cara (construcción) en mm',
               existing_comment='Distancia cara a cara según la norma aplicable',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'bore_mm',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='Diámetro de paso (waterway bore) en mm — la dimensión que el spec llama dn_real',
               existing_comment='Diámetro de paso en mm — equiv. a dn_real del spec_viewer',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'pressure_class',
               existing_type=sa.VARCHAR(length=20),
               comment="Clase de presión aplicable: 'PN6', 'PN10', 'PN16', 'Class 150', 'Class 300'",
               existing_comment='PN6 | PN10 | PN16 | Class 150 | Class 300 | Class 600',
               existing_nullable=True)
    op.alter_column('product_bore_dimensions', 'standard_code',
               existing_type=sa.TEXT(),
               comment="Código completo: 'EN 558 Serie 20', 'ASME B16.10 Class 150', 'AWWA C504'",
               existing_comment="Ej: 'EN 558 Serie 20', 'ASME B16.10 Class 150', 'AWWA C504'",
               existing_nullable=False)
    op.alter_column('product_bore_dimensions', 'standard_system',
               existing_type=sa.VARCHAR(length=16),
               comment='Sistema: DIN | ASME | AWWA | ISO',
               existing_comment='DIN | ASME | AWWA | ISO | JIS | GOST',
               existing_nullable=False)
    op.alter_column('product_bore_dimensions', 'product_sku',
               existing_type=sa.TEXT(),
               comment='SKU del producto',
               existing_nullable=False)
    op.drop_index('uq_assets_bucket_path', table_name='product_assets')
    op.create_unique_constraint(op.f('uq_assets_bucket_path'), 'product_assets', ['bucket', 'storage_path'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_product_assets_hash_sha256'), 'product_assets', ['hash_sha256'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('product_images_storage_path_key'), 'product_assets', ['storage_path'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_product_assets_status'), 'product_assets', ['status'], unique=False, postgresql_where="((status)::text <> 'archived'::text)")
    op.create_index(op.f('idx_product_assets_locale'), 'product_assets', ['locale'], unique=False, postgresql_where='(locale IS NOT NULL)')
    op.alter_column('product_assets', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('pricing_golden_tiers', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_prices_status'), table_name='prices')
    op.drop_index(op.f('ix_prices_product_sku'), table_name='prices')
    op.create_index(op.f('uq_prices_one_approved_active'), 'prices', ['product_sku', 'channel_id', 'scheme_code'], unique=True, postgresql_where="(((status)::text = 'approved'::text) AND (valid_to IS NULL))")
    op.create_index(op.f('idx_prices_updated_at'), 'prices', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_prices_escalated'), 'prices', ['escalated_at'], unique=False, postgresql_where='(escalated = true)')
    op.create_index(op.f('idx_prices_channel_status'), 'prices', ['channel_id', 'status'], unique=False)
    op.create_index(op.f('ix_price_variances_sku'), 'price_variances', ['product_sku'], unique=False)
    op.create_index(op.f('ix_price_variances_period'), 'price_variances', ['fiscal_year', 'period'], unique=False)
    op.alter_column('price_state_transitions', 'to_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('price_state_transitions', 'from_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('ix_price_history_raw_match_marketplace', table_name='price_history_raw')
    op.create_index(op.f('ix_price_history_raw_match_marketplace'), 'price_history_raw', ['match_id', 'marketplace', sa.literal_column('scraped_at DESC')], unique=False)
    op.create_index(op.f('ix_price_history_raw_sku'), 'price_history_raw', ['sku', sa.literal_column('scraped_at DESC')], unique=False, postgresql_where='(sku IS NOT NULL)')
    op.create_index(op.f('ix_price_history_raw_scraped_at'), 'price_history_raw', [sa.literal_column('scraped_at DESC')], unique=False)
    op.alter_column('price_calibration_ranges', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'AED'::bpchar"))
    op.drop_index(op.f('ix_price_approval_events_price_id'), table_name='price_approval_events')
    op.create_index(op.f('ix_price_alerts_notified_at'), 'price_alerts', ['notified_at'], unique=False, postgresql_where='(notified_at IS NULL)')
    op.create_index(op.f('ix_posting_periods_fy'), 'posting_periods', ['fiscal_year', 'period_num'], unique=False)
    op.create_index(op.f('ix_period_close_fy_period'), 'period_close_checklists', ['fiscal_year', 'period_num'], unique=False)
    op.drop_index('idx_payment_terms_code', table_name='payment_terms')
    op.create_index(op.f('ix_payment_runs_status'), 'payment_runs', ['status'], unique=False)
    op.create_index(op.f('ix_payment_runs_date'), 'payment_runs', ['run_date'], unique=False)
    op.create_index(op.f('ix_payment_run_items_run'), 'payment_run_items', ['run_id'], unique=False)
    op.alter_column('model_tech_tables', 'gasket_material',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Solo para kind=pt_curve con múltiples juntas: EPDM | PTFE | GRAFITO',
               existing_nullable=True)
    op.alter_column('model_flow_data', 'mesh_mm',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment=None,
               existing_comment='Tamaño de malla en mm (ej. 1.8, 1.0)',
               existing_nullable=True)
    op.alter_column('model_dimension_rows', 'dn_secondary_mm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Solo para reductores (ej. reducción 1/2 x 3/8): DN salida',
               existing_nullable=True)
    op.alter_column('material_aliases', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.TEXT(),
               postgresql_using='id::text',
               existing_nullable=False)
    op.alter_column('material_aliases', 'source',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='industry_standard | amazon_pdp | erp | manual',
               existing_nullable=True)
    op.create_index(op.f('idx_match_rule_stats_profile'), 'match_rule_stats', ['taxonomy_profile_id'], unique=False)
    op.create_index(op.f('idx_match_rule_stats_candidate'), 'match_rule_stats', ['match_candidate_id'], unique=False)
    op.add_column('match_candidates', sa.Column('vlm_reasoning', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('match_candidates', sa.Column('calibrated_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True))
    op.add_column('match_candidates', sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('match_candidates', sa.Column('vlm_verdict', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('match_candidates', sa.Column('calibrator_version', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('match_candidates', sa.Column('pipeline_version', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('match_candidates', sa.Column('raw_payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_mc_conf_upper'), 'match_candidates', ['conf_upper'], unique=False)
    op.create_index(op.f('idx_mc_conf_lower'), 'match_candidates', ['conf_lower'], unique=False)
    op.create_index(op.f('idx_match_candidates_label'), 'match_candidates', ['label'], unique=False, postgresql_where='(label IS NOT NULL)')
    op.create_index(op.f('idx_match_candidates_calibrated'), 'match_candidates', ['product_sku', 'calibrated_score'], unique=False, postgresql_where='(calibrated_score IS NOT NULL)')
    op.alter_column('match_candidates', 'pack_units',
               existing_type=sa.INTEGER(),
               comment='Unidades por pack (NULL o 1 = precio por unidad individual)',
               existing_nullable=True)
    op.alter_column('match_candidates', 'price_confidence_score',
               existing_type=sa.INTEGER(),
               comment='0-100: confiabilidad del precio según plazo de entrega vs stock UAE',
               existing_nullable=True)
    op.drop_index('uq_last_good_exports_channel_scheme', table_name='last_good_exports')
    op.create_unique_constraint(op.f('uq_last_good_exports_channel_scheme'), 'last_good_exports', ['channel_code', 'scheme_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('last_good_exports', 'scheme_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('last_good_exports', 'channel_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_kg_integrity_results_checked_at'), 'kg_integrity_results', ['checked_at'], unique=False)
    op.alter_column('kg_integrity_results', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'ok'::character varying"),
               existing_nullable=False)
    op.alter_column('kg_integrity_results', 'cdc_lag_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('kg_integrity_results', 'orphan_nodes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('kg_integrity_results', 'edge_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('kg_integrity_results', 'node_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index(op.f('ix_je_controls_user'), 'journal_entry_controls', ['user_id'], unique=False)
    op.create_index(op.f('ix_je_controls_type'), 'journal_entry_controls', ['control_type'], unique=False)
    op.create_index(op.f('idx_invoice_payment_terms_id'), 'invoices', ['payment_terms_id'], unique=False, postgresql_where='(payment_terms_id IS NOT NULL)')
    op.create_index(op.f('idx_invoice_original_id'), 'invoices', ['original_invoice_id'], unique=False, postgresql_where='(original_invoice_id IS NOT NULL)')
    op.create_foreign_key(op.f('fk_inv_pos_warehouse'), 'inventory_positions', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_inv_pos_location'), 'inventory_positions', 'warehouse_locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_inv_pos_lot'), 'inventory_positions', 'inventory_lots', ['lot_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('uix_inv_pos_5d'), 'inventory_positions', ['sku', 'warehouse_id', 'location_id', 'lot_id', 'stock_type'], unique=True, postgresql_where='((location_id IS NOT NULL) AND (lot_id IS NOT NULL))')
    op.create_index(op.f('ix_inv_pos_unrestricted'), 'inventory_positions', ['sku', 'warehouse_id'], unique=False, postgresql_where="(stock_type = 'unrestricted'::text)")
    op.drop_column('inventory_alerts', 'updated_at')
    op.add_column('import_runs', sa.Column('orphans', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index('ix_hitl_queue_match_id', table_name='hitl_queue')
    op.create_index(op.f('ix_hitl_queue_match_id'), 'hitl_queue', ['match_id'], unique=True, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index(op.f('ix_hitl_queue_first_appearance'), 'hitl_queue', ['is_first_appearance', 'priority_score'], unique=False, postgresql_where="(((status)::text = 'pending'::text) AND (is_first_appearance = true))")
    op.drop_index('idx_gr_received_at', table_name='goods_receipts', postgresql_ops={'received_at': 'DESC'})
    op.create_index(op.f('idx_gr_received_at'), 'goods_receipts', [sa.literal_column('received_at DESC')], unique=False)
    op.create_index(op.f('ix_gl_accounts_type'), 'gl_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_gl_accounts_code'), 'gl_accounts', ['account_code'], unique=False)
    op.create_index(op.f('idx_fx_lookup_desc'), 'fx_rates', ['from_currency', 'to_currency', sa.literal_column('effective_from DESC')], unique=False)
    op.drop_index('ix_force_logout_user_created', table_name='force_logout_events')
    op.create_index(op.f('ix_force_logout_user_created'), 'force_logout_events', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('family_schemas', 'json_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON Schema Draft 2020-12; validado client + server',
               existing_nullable=False)
    op.alter_column('family_schemas', 'family_slug',
               existing_type=sa.TEXT(),
               comment='Slug de familia (corresponde a families.code o registry futuro). Sin FK por ahora — evolutivo.',
               existing_nullable=False)
    op.create_index(op.f('idx_exception_rules_active_channel'), 'exception_rules', ['active', 'channel_id'], unique=False)
    op.create_index(op.f('uq_dn_nps_ref_dn'), 'dn_nps_reference', ['dn_nominal'], unique=True)
    op.alter_column('dn_nps_reference', 'notes',
               existing_type=sa.TEXT(),
               comment='Aclaraciones o excepciones de norma',
               existing_nullable=True)
    op.alter_column('dn_nps_reference', 'nps_label',
               existing_type=sa.TEXT(),
               comment='Etiqueta legible NPS: \'3"\', \'4"\', \'6"\'',
               existing_comment='Etiqueta legible: \'3"\', \'4"\'',
               existing_nullable=False)
    op.alter_column('dn_nps_reference', 'nps_nominal',
               existing_type=sa.TEXT(),
               comment="Tamaño nominal americano: '3', '4', '6' (sin comillas)",
               existing_comment="NPS sin comillas: '3', '4', '6'",
               existing_nullable=False)
    op.alter_column('dn_nps_reference', 'dn_nominal',
               existing_type=sa.TEXT(),
               comment="Tamaño nominal métrico: '80', '100', '150' (sin prefijo DN)",
               existing_comment="Tamaño nominal métrico sin prefijo DN: '80', '100'",
               existing_nullable=False)
    op.create_index(op.f('idx_open_items_open'), 'customer_open_items', ['customer_id', 'status'], unique=False, postgresql_where="(status <> 'paid'::text)")
    op.drop_index(op.f('ix_costs_sku'), table_name='costs')
    op.drop_index('idx_costs_active_unique_lookup', table_name='costs', postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('uq_costs_active_combo'), 'costs', ['sku', 'scheme_code', sa.literal_column("COALESCE(supplier_code, ''::text)")], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.alter_column('costs', 'currency_origin',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'AED'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_cost_centers_code'), 'cost_centers', ['cc_code'], unique=False)
    op.create_index(op.f('ix_competitor_listings_embedding_hnsw'), 'competitor_listings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('channels', 'name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_budgets_account'), 'budgets', ['gl_account_id'], unique=False)
    op.alter_column('audit_hash_state', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.create_index(op.f('idx_audit_events_entity_type_event_at'), 'audit_events', ['entity_type', sa.literal_column('event_at DESC')], unique=False)
    op.create_index(op.f('ix_av_attr_number'), 'attribute_values', ['attribute_id', 'value_number'], unique=False, postgresql_where='(value_number IS NOT NULL)')
    # ### end Alembic commands ###
